spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
      show-sql: true
  datasource:
    url: jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_ROOT_PASSWORD}
    testWhileIdle: true
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
security:
  jwt:
    token:
      expire-length: 1800000 # 30 minutes duration: 30 minutes * 60 seconds * 1000 miliseconds